const menuList = [
    {
        title: "首页",
        key: '/admin/home'
    },
    {
        title:"安全目标",
        key: "/admin/security_goal",
        children:[
            {
                title:"企业目标",
                key:"/admin/enterprise_goal"
            },
            {
                title:"项目目标",
                key:"/admin/project_goal"
            },
        ]
    },
    {
        title:"安全规范",
        key: "/admin/safety_specification",
        children:[
            {
                title:"法律法规",
                key:"/admin/laws_regulations"
            },
            {
                title:"安全生产责任制",
                key:"/admin/safety_production"
            },
            {
                title:"操作规程",
                key:"/admin/operating_rules"
            },
            {
                title:"应急预案",
                key:"/admin/emergency_plan"
            },
        ]
    },
    {
        title:"安全措施",
        key:"/admin/safety_measures",
        children:[
            {
                title:"安全管理协议",
                key:"/admin/security_management_protocol"
            },
            {
                title:"入场人员清单",
                key:"/admin/admission_list"
            },
            {
                title:"特种作业人员台帐",
                key:"/admin/special_account"
            },
            {
                title:"设备验收台帐",
                key:"/admin/equipment_account"
            },
            {
                title:"安全物资台帐",
                key:"/admin/material_account"
            },
            {
                title:"安全技术交底台帐",
                key:"/admin/technology_account"
            },
            {
                title:"安全培训台帐",
                key:"/admin/training_account"
            },
            {
                title:"安全生产例会台帐",
                key:"/admin/safety_meeting_account"
            },
            {
                title:"应急演练记录",
                key:"/admin/emergency_drill_record"
            },
            {
                title:"违规处罚记录",
                key:"/admin/violation_penalty_record"
            },
        ]
    },
    {
        title:"安全监督",
        key:"/admin/manage_download",
        children:[
            {
                title:"安全日报",
                key:"/admin/safety_daily"
            },
            {
                title:"项目安全检查周报",
                key:"/admin/safety_weekly_report"
            },
            {
                title:"专项安全检查记录",
                key:"/admin/safety_inspection_record"
            },
            {
                title:"隐患统计台帐",
                key:"/admin/hidden_danger_statistics"
            },
            {
                title:"隐患整改报告",
                key:"/admin/rectification_report"
            },
        ]
    },
    {
        title:"重点部位动态报告",
        key:"/admin/activities",
        children:[
            {
                title:"动火作业",
                key:"/admin/fire_operation"
            },
            {
                title:"登高作业",
                key:"/admin/climbing_operation"
            },
            {
                title:"吊装作业",
                key:"/admin/hoisting_operation"
            },
        ]
    },
    {
        title:"事故报告",
        key:"/admin/user_info",
        children:[
            {
                title:"事故统计",
                key:"/admin/accident_statistics"
            },
            {
                title:"事故分析",
                key:"/admin/accident_analysis"
            },
            {
                title:"事故报告",
                key:"/admin/accident_report"
            },
        ]
    },
    {
        title:"个人中心",
        key:"/admin/manage_user",
        children:[
            {
                title:"密码修改",
                key:"/admin/password_modification"
            },
            {
                title:"安保准入",
                key:"/admin/security_access"
            },
            {
                title:"物资申报",
                key:"/admin/material_declaration"
            },
        ]
    }
];

export default menuList;